FROM node:16-alpine
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

ADD . /app/src
WORKDIR /app/src

CMD ["npm", "start"]