API_ADDRESS_NEEDS = "https://hackaton.donorsearch.org/api/address_needs/"
API_ADDRESS_NEEDS_ID = "https://hackaton.donorsearch.org/api/address_needs/{}/"
API_AUTH_CHANGE_EMAIL = "https://hackaton.donorsearch.org/api/auth/change_email/"
API_AUTH_CHANGE_PASSWORD = "https://hackaton.donorsearch.org/api/auth/change_password/"
API_AUTH_CHANGE_PHONE = "https://hackaton.donorsearch.org/api/auth/change_phone/"
API_AUTH_CONFIRM_EMAIL = "https://hackaton.donorsearch.org/api/auth/confirm_email/"
API_AUTH_CONFIRM_PHONE = "https://hackaton.donorsearch.org/api/auth/confirm_phone/"
API_AUTH_DONOR_CARD = "https://hackaton.donorsearch.org/api/auth/donor_card/"
API_AUTH_ME = "https://hackaton.donorsearch.org/api/auth/me/"
API_AUTH_CHECK_SMS_DOE = "https://hackaton.donorsearch.org/api/auth/check_sms_code/"
API_AUTH_RECOVER = "https://hackaton.donorsearch.org/api/auth/recover/"
API_AUTH_RESEND_CODE = "https://hackaton.donorsearch.org/api/auth/resend_code/"
API_AUTH_RESEND_EMAIL_CODE = "https://hackaton.donorsearch.org/api/auth/resend_code/"
API_AUTH_SET_PASSWORD = "https://hackaton.donorsearch.org/api/auth/set_password/"
API_AUTH_CONFIRM_EMAIL_REG = "https://hackaton.donorsearch.org/api/auth/confirm_email_reg/"
API_AUTH_CONFIRM_PHONE_REG = "https://hackaton.donorsearch.org/api/auth/confirm_phone_reg/"
API_AUTH_REGISTRATION = "https://hackaton.donorsearch.org/api/auth/registration/"
API_AUTH_LOGIN = "https://hackaton.donorsearch.org/api/auth/login/"
API_AUTH_LOGOUT = "https://hackaton.donorsearch.org/api/auth/logout/"
API_BLOOD_STATIONS = "https://hackaton.donorsearch.org/api/blood_stations/"
API_BLOOD_STATIONS_ID = "https://hackaton.donorsearch.org/api/blood_stations/"
API_BLOOD_STATIONS_ID_PLANNED = "https://hackaton.donorsearch.org/api/blood_stations/"
API_BLOOD_STATIONS_ID_TOP = "https://hackaton.donorsearch.org/api/blood_stations/{}/top/"
API_BLOOD_STATIONS_ID_TOP_HALFYEAR = "https://hackaton.donorsearch.org/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_ALL_NAMES = "https://hackaton.donorsearch.org/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_MAP = "https://hackaton.donorsearch.org/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_SEARCH = "https://hackaton.donorsearch.org/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_SELECTED = "https://hackaton.donorsearch.org/api/blood_stations/selected/"
API_NEEDS = "https://hackaton.donorsearch.org/api/needs/"
API_NEEDS_ID = "https://hackaton.donorsearch.org/api/needs/{}/"
API_NEEDS_AVAILABLE = "https://hackaton.donorsearch.org/api/needs/available/"
API_BONUSES = "https://hackaton.donorsearch.org/api/bonuses/"
API_BONUSES_ID = "https://hackaton.donorsearch.org/api/bonuses/{}/"
API_BONUSES_ID_FEEDBACK = "https://hackaton.donorsearch.org/api/bonuses/{}/feedback/"
API_CITIES = "https://hackaton.donorsearch.org/api/cities/"
API_CITIES_ID = "https://hackaton.donorsearch.org/api/cities/{}/"
API_CITIES_BY_LOCATION = "https://hackaton.donorsearch.org/api/cities/by_location/"
API_COUNTRIES = "https://hackaton.donorsearch.org/api/cities/by_location/"
API_COUNTRIES_ID = "https://hackaton.donorsearch.org/api/countries/{}/"
API_REGIONS = "https://hackaton.donorsearch.org/api/regions/"
API_REGIONS_ID = "https://hackaton.donorsearch.org/api/regions/{}/"
API_EVENTS = "https://hackaton.donorsearch.org/api/events/"
API_EVENTS_ID = "https://hackaton.donorsearch.org/api/events/{}/"
API_PICTURE = "https://hackaton.donorsearch.org/api/picture/"
API_USERS_TOP = "https://hackaton.donorsearch.org/api/picture/"
API_DONATION_PLAN = "https://hackaton.donorsearch.org/api/donation_plan/"
API_DONATION_PLAN_ID = "https://hackaton.donorsearch.org/api/donation_plan/{}/"
API_DONATION_PLAN_LATEST = "https://hackaton.donorsearch.org/api/donation_plan/latest/"
API_DONATIONS = "https://hackaton.donorsearch.org/api/donations/"
API_DONATIONS_ID = "https://hackaton.donorsearch.org/api/donations/{}/"
API_DONATIONS_IS_EXISTS = "https://hackaton.donorsearch.org/api/donations/is_exists/"






