API_ADDRESS_NEEDS = "/api/address_needs/"
API_ADDRESS_NEEDS_ID = "/api/address_needs/{}/"
API_AUTH_CHANGE_EMAIL = "/api/auth/change_email/"
API_AUTH_CHANGE_PASSWORD = "/api/auth/change_password/"
API_AUTH_CHANGE_PHONE = "/api/auth/change_phone/"
API_AUTH_CONFIRM_EMAIL = "/api/auth/confirm_email/"
API_AUTH_CONFIRM_PHONE = "/api/auth/confirm_phone/"
API_AUTH_DONOR_CARD = "/api/auth/donor_card/"
API_AUTH_ME = "/api/auth/me/"
API_AUTH_CHECK_SMS_DOE = "/api/auth/check_sms_code/"
API_AUTH_RECOVER = "/api/auth/recover/"
API_AUTH_RESEND_CODE = "/api/auth/resend_code/"
API_AUTH_RESEND_EMAIL_CODE = "/api/auth/resend_code/"
API_AUTH_SET_PASSWORD = "/api/auth/set_password/"
API_AUTH_CONFIRM_EMAIL_REG = "/api/auth/confirm_email_reg/"
API_AUTH_CONFIRM_PHONE_REG = "/api/auth/confirm_phone_reg/"
API_AUTH_REGISTRATION = "/api/auth/confirm_phone_reg/"
API_AUTH_LOGIN = "/api/auth/login/"
API_AUTH_LOGOUT = "/api/auth/logout/"
API_BLOOD_STATIONS = "/api/blood_stations/"
API_BLOOD_STATIONS_ID = "/api/blood_stations/"
API_BLOOD_STATIONS_ID_PLANNED = "/api/blood_stations/"
API_BLOOD_STATIONS_ID_TOP = "/api/blood_stations/{}/top/"
API_BLOOD_STATIONS_ID_TOP_HALFYEAR = "/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_ALL_NAMES = "/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_MAP = "/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_SEARCH = "/api/blood_stations/{}/top_halfyear/"
API_BLOOD_STATIONS_SELECTED = "/api/blood_stations/selected/"
API_NEEDS = "/api/needs/"
API_NEEDS_ID = "/api/needs/{}/"
API_NEEDS_AVAILABLE = "/api/needs/available/"
API_BONUSES = "/api/bonuses/"
API_BONUSES_ID = "/api/bonuses/{}/"
API_BONUSES_ID_FEEDBACK = "/api/bonuses/{}/feedback/"
API_CITIES = "/api/cities/"
API_CITIES_ID = "/api/cities/{}/"
API_CITIES_BY_LOCATION = "/api/cities/by_location/"
API_COUNTRIES = "/api/cities/by_location/"
API_COUNTRIES_ID = "/api/countries/{}/"
API_REGIONS = "/api/regions/"
API_REGIONS_ID = "/api/regions/{}/"
API_EVENTS = "/api/events/"
API_EVENTS_ID = "/api/events/{}/"
API_PICTURE = "/api/picture/"
API_USERS_TOP = "/api/picture/"
API_DONATION_PLAN = "/api/donation_plan/"
API_DONATION_PLAN_ID = "/api/donation_plan/{}/"
API_DONATION_PLAN_LATEST = "/api/donation_plan/latest/"
API_DONATIONS = "/api/donations/"
API_DONATIONS_ID = "/api/donations/{}/"
API_DONATIONS_IS_EXISTS = "/api/donations/is_exists/"






