version: '3.8'

services:

  backend:
    build:  ./backend
    restart: always
    ports:  
      -"8888:8888"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      -./frontend:/usr/src/app
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data